[package]
name = "catering"
version = "0.1.0"
authors = ["ricky han <github@rickyhan.com>"]
edition = "2018"

[dependencies]

[dependencies.quicksilver]
version = "0.3.0"
default-features = false
features = [
    "sounds",
    "fonts"
]
